<?php

return [
    /**
     * Mapeamento de módulos e suas permissões relacionadas
     * Baseado na estrutura de menus do sistema
     */
    'modules' => [
        // ========================================
        // ABASTECIMENTOS
        // ========================================
        'abastecimentos' => [
            // Abastecimento base
            'ver_abastecimento',
            'criar_abastecimento',
            'editar_abastecimento',
            'excluir_abastecimento',

            // Abastecimento Manual
            'ver_abastecimentomanual',
            'criar_abastecimentomanual',
            'editar_abastecimentomanual',
            'excluir_abastecimentomanual',

            // Abastecimento ATS/TruckPag
            'ver_abastecimentoatstruckpagmanual',
            'criar_abastecimentoatstruckpagmanual',
            'editar_abastecimentoatstruckpagmanual',
            'excluir_abastecimentoatstruckpagmanual',
            'ver_abastecimentotruckpag',
            'criar_abastecimentotruckpag',
            'editar_abastecimentotruckpag',
            'excluir_abastecimentotruckpag',

            // Integrações
            'ver_abastecimentointegracao',
            'criar_abastecimentointegracao',
            'editar_abastecimentointegracao',
            'excluir_abastecimentointegracao',

            // Itens
            'ver_abastecimentoitem',
            'criar_abastecimentoitem',
            'editar_abastecimentoitem',
            'excluir_abastecimentoitem',

            // Faturamento
            'ver_abastecimentosfaturamento',
            'criar_abastecimentosfaturamento',
            'editar_abastecimentosfaturamento',
            'excluir_abastecimentosfaturamento',

            // Ajuste KM
            'ver_ajustekmabastecimento',
            'criar_ajustekmabastecimento',
            'editar_ajustekmabastecimento',
            'excluir_ajustekmabastecimento',

            // Encerrantes/Bombas
            'ver_encerrante',
            'criar_encerrante',
            'editar_encerrante',
            'excluir_encerrante',
            'ver_bomba',
            'criar_bomba',
            'editar_bomba',
            'excluir_bomba',

            // Permissões KM Manual
            'ver_permissaokmmanual',
            'criar_permissaokmmanual',
            'editar_permissaokmmanual',
            'excluir_permissaokmmanual',

            // Aferição
            'ver_entradaafericaoabastecimento',
            'criar_entradaafericaoabastecimento',
            'editar_entradaafericaoabastecimento',
            'excluir_entradaafericaoabastecimento',

            // Recebimento Combustíveis
            'ver_recebimentocombustivel',
            'criar_recebimentocombustivel',
            'editar_recebimentocombustivel',
            'excluir_recebimentocombustivel',

            // Tanques
            'ver_tanque',
            'criar_tanque',
            'editar_tanque',
            'excluir_tanque',

            // Valor Combustível
            'ver_valorcombustivelterceiro',
            'criar_valorcombustivelterceiro',
            'editar_valorcombustivelterceiro',
            'excluir_valorcombustivelterceiro',

            // Histórico/Estoque
            'ver_historicoabastecimentobaixarestoque',
            'criar_historicoabastecimentobaixarestoque',
            'editar_historicoabastecimentobaixarestoque',
            'excluir_historicoabastecimentobaixarestoque',
            'ver_estoquecombustivel',
            'criar_estoquecombustivel',
            'editar_estoquecombustivel',
            'excluir_estoquecombustivel',
            'ver_vestoquecombustivel',
            'criar_vestoquecombustivel',
            'editar_vestoquecombustivel',
            'excluir_vestoquecombustivel',

            // VVL Atual
            'ver_vvlratualabastecimento',
            'criar_vvlratualabastecimento',
            'editar_vvlratualabastecimento',
            'excluir_vvlratualabastecimento',

            // Inconsistências
            'ver_inconsistenciaats',
            'criar_inconsistenciaats',
            'editar_inconsistenciaats',
            'excluir_inconsistenciaats',
            'ver_inconsistenciatruckpag',
            'criar_inconsistenciatruckpag',
            'editar_inconsistenciatruckpag',
            'excluir_inconsistenciatruckpag',
        ],

        // ========================================
        // COMPRAS
        // ========================================
        'compras' => [
            // Solicitações
            'ver_solicitacaocompras',
            'criar_solicitacao_compra',
            'editar_solicitacao_compra',
            'excluir_solicitacao_compra',
            'aprovar_solicitacao_compra',
            'rejeitar_solicitacao_compra',
            'visualizar_solicitacao_compra',

            // Pedidos
            'ver_pedidocompras',
            'criar_pedido_compra',
            'editar_pedido_compra',
            'excluir_pedido_compra',
            'aprovar_pedido_compra',
            'aprovar_pedido_compra_nivel_1',
            'aprovar_pedido_compra_nivel_2',
            'aprovar_pedido_compra_nivel_3',
            'aprovar_pedido_compra_nivel_4',
            'rejeitar_pedido_compra',
            'cancelar_pedido_compra',
            'enviar_pedido_compra',
            'visualizar_pedido_compra',

            // Orçamentos
            'criar_orcamento',
            'editar_orcamento',
            'excluir_orcamento',
            'aprovar_orcamento',
            'rejeitar_orcamento',
            'visualizar_orcamento',

            // Notas Fiscais
            'criar_nota_fiscal',
            'editar_nota_fiscal',
            'excluir_nota_fiscal',
            'aprovar_nota_fiscal',
            'visualizar_nota_fiscal',

            // Contratos
            'criar_contrato',
            'editar_contrato',
            'excluir_contrato',
            'visualizar_contrato',

            // Itens
            'ver_itenspedidos',
            'criar_itenspedidos',
            'editar_itenspedidos',
            'excluir_itenspedidos',

            // Relatórios
            'exportar_relatorios_compras',
            'visualizar_relatorios_compras',
        ],

        // ========================================
        // ESTOQUE
        // ========================================
        'estoque' => [
            // Estoque Base
            'ver_estoque',
            'criar_estoque',
            'editar_estoque',
            'excluir_estoque',

            // Produtos
            'ver_produto',
            'criar_produto',
            'editar_produto',
            'excluir_produto',
            'ver_produtoporfilial',
            'criar_produtoporfilial',
            'editar_produtoporfilial',
            'excluir_produtoporfilial',
            'ver_produtosporfilial',
            'criar_produtosporfilial',
            'editar_produtosporfilial',
            'excluir_produtosporfilial',
            'ver_produtoxaplicacao',
            'criar_produtoxaplicacao',
            'editar_produtoxaplicacao',
            'excluir_produtoxaplicacao',

            // Ajustes
            'ver_ajusteestoque',
            'criar_ajusteestoque',
            'editar_ajusteestoque',
            'excluir_ajusteestoque',

            // Transferências
            'ver_transferenciaestoque',
            'criar_transferenciaestoque',
            'editar_transferenciaestoque',
            'excluir_transferenciaestoque',
            'ver_transferenciaestoqueitens',
            'criar_transferenciaestoqueitens',
            'editar_transferenciaestoqueitens',
            'excluir_transferenciaestoqueitens',
            'ver_transferenciaestoqueaux',
            'criar_transferenciaestoqueaux',
            'editar_transferenciaestoqueaux',
            'excluir_transferenciaestoqueaux',
            'ver_transferenciaestoqueauxenvio',
            'criar_transferenciaestoqueauxenvio',
            'editar_transferenciaestoqueauxenvio',
            'excluir_transferenciaestoqueauxenvio',
            'ver_transferenciadiretaestoque',
            'criar_transferenciadiretaestoque',
            'editar_transferenciadiretaestoque',
            'excluir_transferenciadiretaestoque',

            // Devoluções
            'ver_devolucaomateriais',
            'criar_devolucaomateriais',
            'editar_devolucaomateriais',
            'excluir_devolucaomateriais',
            'ver_devolucaoprodutoordem',
            'criar_devolucaoprodutoordem',
            'editar_devolucaoprodutoordem',
            'excluir_devolucaoprodutoordem',
            'ver_devolucaotransferenciaestoquerequisicao',
            'criar_devolucaotransferenciaestoquerequisicao',
            'editar_devolucaotransferenciaestoquerequisicao',
            'excluir_devolucaotransferenciaestoquerequisicao',

            // Histórico
            'ver_historicomovimentacaoestoque',
            'criar_historicomovimentacaoestoque',
            'editar_historicomovimentacaoestoque',
            'excluir_historicomovimentacaoestoque',

            // Solicitações
            'ver_produtossolicitacoes',
            'criar_produtossolicitacoes',
            'editar_produtossolicitacoes',
            'excluir_produtossolicitacoes',

            // Requisições de Materiais
            'criar_requisicao_material',
            'editar_requisicao_material',
            'visualizar_requisicao_material',
            'excluir_requisicao_material',
            'aprovar_requisicao_material',
            'rejeitar_requisicao_material',
            'cancelar_requisicao_material',
            'finalizar_requisicao_material',
            'ver_requisicaomaterial',
        ],

        // ========================================
        // VEÍCULOS
        // ========================================
        'veiculos' => [
            // Veículos Base
            'ver_veiculo',
            'criar_veiculo',
            'editar_veiculo',
            'excluir_veiculo',
            'ver_baseveiculo',
            'criar_baseveiculo',
            'editar_baseveiculo',
            'excluir_baseveiculo',

            // Certificados
            'ver_certificadoveiculos',
            'criar_certificadoveiculos',
            'editar_certificadoveiculos',
            'excluir_certificadoveiculos',

            // Licenciamento
            'ver_licenciamentoveiculo',
            'criar_licenciamentoveiculo',
            'editar_licenciamentoveiculo',
            'excluir_licenciamentoveiculo',

            // IPVA
            'ver_ipvaveiculo',
            'criar_ipvaveiculo',
            'editar_ipvaveiculo',
            'excluir_ipvaveiculo',
            'ver_parcelasipva',
            'criar_parcelasipva',
            'editar_parcelasipva',
            'excluir_parcelasipva',

            // Seguro Obrigatório
            'ver_seguroobrigatorio',
            'criar_seguroobrigatorio',
            'editar_seguroobrigatorio',
            'excluir_seguroobrigatorio',

            // Teste de Fumaça
            'ver_testefumaca',
            'criar_testefumaca',
            'editar_testefumaca',
            'excluir_testefumaca',

            // Transferências
            'ver_transferenciaveiculo',
            'criar_transferenciaveiculo',
            'editar_transferenciaveiculo',
            'excluir_transferenciaveiculo',

            // Atrelamentos
            'ver_atrelamentoveiculo',
            'criar_atrelamentoveiculo',
            'editar_atrelamentoveiculo',
            'excluir_atrelamentoveiculo',
            'ver_atrelamentoitens',
            'criar_atrelamentoitens',
            'editar_atrelamentoitens',
            'excluir_atrelamentoitens',

            // Veículo x Pneu
            'ver_veiculoxpneu',
            'criar_veiculoxpneu',
            'editar_veiculoxpneu',
            'excluir_veiculoxpneu',

            // KM Comodato
            'ver_kmcomotado',
            'criar_kmcomotado',
            'editar_kmcomotado',
            'excluir_kmcomotado',
        ],

        // ========================================
        // MANUTENÇÃO
        // ========================================
        'manutencao' => [
            // Manutenção Base
            'ver_manutencao',
            'criar_manutencao',
            'editar_manutencao',
            'excluir_manutencao',

            // Ordem de Serviço
            'ver_ordemservico',
            'criar_ordemservico',
            'editar_ordemservico',
            'excluir_ordemservico',
            'ver_ordemservicopecas',
            'criar_ordemservicopecas',
            'editar_ordemservicopecas',
            'excluir_ordemservicopecas',
            'ver_ordemservicoservicos',
            'criar_ordemservicoservicos',
            'editar_ordemservicoservicos',
            'excluir_ordemservicoservicos',
            'ver_ordemservicopecasimobilizados',
            'criar_ordemservicopecasimobilizados',
            'editar_ordemservicopecasimobilizados',
            'excluir_ordemservicopecasimobilizados',

            // Pré-Ordem
            'ver_preordemservico',
            'criar_preordemservico',
            'editar_preordemservico',
            'excluir_preordemservico',
            'ver_preordemservicoservicos',
            'criar_preordemservicoservicos',
            'editar_preordemservicoservicos',
            'excluir_preordemservicoservicos',

            // Status
            'ver_statusordemservico',
            'criar_statusordemservico',
            'editar_statusordemservico',
            'excluir_statusordemservico',

            // Planejamento
            'ver_planejamentomanutencao',
            'criar_planejamentomanutencao',
            'editar_planejamentomanutencao',
            'excluir_planejamentomanutencao',
            'ver_categoriaplanejamentomanutencao',
            'criar_categoriaplanejamentomanutencao',
            'editar_categoriaplanejamentomanutencao',
            'excluir_categoriaplanejamentomanutencao',
            'ver_servicoplanejamentomanutencao',
            'criar_servicoplanejamentomanutencao',
            'editar_servicoplanejamentomanutencao',
            'excluir_servicoplanejamentomanutencao',

            // Serviços
            'ver_servico',
            'criar_servico',
            'editar_servico',
            'excluir_servico',
            'ver_servicos',
            'criar_servicos',
            'editar_servicos',
            'excluir_servicos',
            'ver_servicosmecanico',
            'criar_servicosmecanico',
            'editar_servicosmecanico',
            'excluir_servicosmecanico',
            'ver_servicoxfornecedor',
            'criar_servicoxfornecedor',
            'editar_servicoxfornecedor',
            'excluir_servicoxfornecedor',

            // Peças
            'ver_pecasservicos',
            'criar_pecasservicos',
            'editar_pecasservicos',
            'excluir_pecasservicos',

            // Controle
            'ver_vcontrolemanutencaofrota',
            'criar_vcontrolemanutencaofrota',
            'editar_vcontrolemanutencaofrota',
            'excluir_vcontrolemanutencaofrota',
            'ver_v_manutencao_abertas',
            'criar_v_manutencao_abertas',
            'editar_v_manutencao_abertas',
            'excluir_v_manutencao_abertas',
            'ver_vultimasmanutencoesveiculo',
            'criar_vultimasmanutencoesveiculo',
            'editar_vultimasmanutencoesveiculo',
            'excluir_vultimasmanutencoesveiculo',
            'ver_vultimaspreventivasveiculo',
            'criar_vultimaspreventivasveiculo',
            'editar_vultimaspreventivasveiculo',
            'excluir_vultimaspreventivasveiculo',

            // Despesas
            'ver_despesasveiculos',
            'criar_despesasveiculos',
            'editar_despesasveiculos',
            'excluir_despesasveiculos',

            // NFe
            'ver_nfordemservico',
            'criar_nfordemservico',
            'editar_nfordemservico',
            'excluir_nfordemservico',
            'ver_notafiscalservico',
            'criar_notafiscalservico',
            'editar_notafiscalservico',
            'excluir_notafiscalservico',
            'ver_notafiscalservicoitens',
            'criar_notafiscalservicoitens',
            'editar_notafiscalservicoitens',
            'excluir_notafiscalservicoitens',
        ],

        // ========================================
        // PNEUS
        // ========================================
        'pneus' => [
            // Pneus Base
            'ver_pneu',
            'criar_pneu',
            'editar_pneu',
            'excluir_pneu',
            'ver_historicopneu',
            'criar_historicopneu',
            'editar_historicopneu',
            'excluir_historicopneu',

            // Contagem
            'ver_contagempneu',
            'criar_contagempneu',
            'editar_contagempneu',
            'excluir_contagempneu',

            // Manutenção
            'ver_manutencaopneus',
            'criar_manutencaopneus',
            'editar_manutencaopneus',
            'excluir_manutencaopneus',
            'ver_manutencaopneusentrada',
            'criar_manutencaopneusentrada',
            'editar_manutencaopneusentrada',
            'excluir_manutencaopneusentrada',
            'ver_manutencaopneusitens',
            'criar_manutencaopneusitens',
            'editar_manutencaopneusitens',
            'excluir_manutencaopneusitens',
            'ver_manutencaopneusentradaitens',
            'criar_manutencaopneusentradaitens',
            'editar_manutencaopneusentradaitens',
            'excluir_manutencaopneusentradaitens',

            // Aplicados
            'ver_pneusaplicados',
            'criar_pneusaplicados',
            'editar_pneusaplicados',
            'excluir_pneusaplicados',

            // Descarte
            'ver_descartepneu',
            'criar_descartepneu',
            'editar_descartepneu',
            'excluir_descartepneu',

            // Transferência
            'ver_transferenciapneus',
            'criar_transferenciapneus',
            'editar_transferenciapneus',
            'excluir_transferenciapneus',
            'ver_transferenciapneuitens',
            'criar_transferenciapneuitens',
            'editar_transferenciapneuitens',
            'excluir_transferenciapneuitens',
            'ver_transferenciapneusmodelos',
            'criar_transferenciapneusmodelos',
            'editar_transferenciapneusmodelos',
            'excluir_transferenciapneusmodelos',

            // Requisições
            'ver_requisicaopneu',
            'criar_requisicaopneu',
            'editar_requisicaopneu',
            'excluir_requisicaopneu',
            'ver_requisicaopneuitens',
            'criar_requisicaopneuitens',
            'editar_requisicaopneuitens',
            'excluir_requisicaopneuitens',
            'ver_requisicaopneumodelos',
            'criar_requisicaopneumodelos',
            'editar_requisicaopneumodelos',
            'excluir_requisicaopneumodelos',

            // Modelos
            'ver_modelopneu',
            'criar_modelopneu',
            'editar_modelopneu',
            'excluir_modelopneu',
        ],

        // ========================================
        // IMOBILIZADOS
        // ========================================
        'imobilizados' => [
            // Relação Imobilizado
            'ver_relacaoimobilizado',
            'criar_relacaoimobilizado',
            'editar_relacaoimobilizado',
            'excluir_relacaoimobilizado',
            'ver_relacaoimobilizadoitens',
            'criar_relacaoimobilizadoitens',
            'editar_relacaoimobilizadoitens',
            'excluir_relacaoimobilizadoitens',

            // Solicitação Peças
            'ver_relacaosolicitacaoespecas',
            'criar_relacaosolicitacaoespecas',
            'editar_relacaosolicitacaoespecas',
            'excluir_relacaosolicitacaoespecas',

            // Requisições
            'ver_vrequisicaoprodutoos',
            'criar_vrequisicaoprodutoos',
            'editar_vrequisicaoprodutoos',
            'excluir_vrequisicaoprodutoos',

            // Tipos
            'ver_tipomanutencaoimobilizado',
            'criar_tipomanutencaoimobilizado',
            'editar_tipomanutencaoimobilizado',
            'excluir_tipomanutencaoimobilizado',
        ],

        // ========================================
        // PESSOAL
        // ========================================
        'pessoal' => [
            // Pessoal Base
            'ver_pessoal',
            'criar_pessoal',
            'editar_pessoal',
            'excluir_pessoal',

            // Motorista
            'ver_motorista',
            'criar_motorista',
            'editar_motorista',
            'excluir_motorista',

            // Dados Pessoal Sinistro
            'ver_dadospessoalsinistro',
            'criar_dadospessoalsinistro',
            'editar_dadospessoalsinistro',
            'excluir_dadospessoalsinistro',
        ],

        // ========================================
        // FORNECEDORES
        // ========================================
        'fornecedores' => [
            'ver_fornecedor',
            'criar_fornecedor',
            'editar_fornecedor',
            'excluir_fornecedor',
            'visualizar_fornecedor',
            'ver_fornecedorxmecanico',
            'criar_fornecedorxmecanico',
            'editar_fornecedorxmecanico',
            'excluir_fornecedorxmecanico',
        ],

        // ========================================
        // SINISTROS
        // ========================================
        'sinistros' => [
            'ver_sinistro',
            'criar_sinistro',
            'editar_sinistro',
            'excluir_sinistro',
            'ver_fotosdocumentossinistros',
            'criar_fotosdocumentossinistros',
            'editar_fotosdocumentossinistros',
            'excluir_fotosdocumentossinistros',
            'ver_historicoeventossinistro',
            'criar_historicoeventossinistro',
            'editar_historicoeventossinistro',
            'excluir_historicoeventossinistro',
        ],

        // ========================================
        // MULTAS
        // ========================================
        'multas' => [
            'ver_multa',
            'criar_multa',
            'editar_multa',
            'excluir_multa',
            'ver_classificacaomulta',
            'criar_classificacaomulta',
            'editar_classificacaomulta',
            'excluir_classificacaomulta',
            'ver_detalhemulta',
            'criar_detalhemulta',
            'editar_detalhemulta',
            'excluir_detalhemulta',
        ],

        // ========================================
        // CHECKLIST
        // ========================================
        'checklist' => [
            'ver_checklist',
            'criar_checklist',
            'editar_checklist',
            'excluir_checklist',
            'ver_checklistresposta',
            'criar_checklistresposta',
            'editar_checklistresposta',
            'excluir_checklistresposta',
            'ver_colunachecklist',
            'criar_colunachecklist',
            'editar_colunachecklist',
            'excluir_colunachecklist',
        ],

        // ========================================
        // CONFIGURAÇÕES/TIPOS
        // ========================================
        'configuracoes' => [
            // Tipos gerais
            'ver_tipoacertoestoque',
            'criar_tipoacertoestoque',
            'editar_tipoacertoestoque',
            'excluir_tipoacertoestoque',
            'ver_tipoborrachapneu',
            'criar_tipoborrachapneu',
            'editar_tipoborrachapneu',
            'excluir_tipoborrachapneu',
            'ver_tipocategoria',
            'criar_tipocategoria',
            'editar_tipocategoria',
            'excluir_tipocategoria',
            'ver_tipocertificado',
            'criar_tipocertificado',
            'editar_tipocertificado',
            'excluir_tipocertificado',
            'ver_tipochecklist',
            'criar_tipochecklist',
            'editar_tipochecklist',
            'excluir_tipochecklist',
            'ver_tipocombustivel',
            'criar_tipocombustivel',
            'editar_tipocombustivel',
            'excluir_tipocombustivel',
            'ver_tipodescarte',
            'criar_tipodescarte',
            'editar_tipodescarte',
            'excluir_tipodescarte',
            'ver_tipodesenhopneu',
            'criar_tipodesenhopneu',
            'editar_tipodesenhopneu',
            'excluir_tipodesenhopneu',
            'ver_tipodespesas',
            'criar_tipodespesas',
            'editar_tipodespesas',
            'excluir_tipodespesas',
            'ver_tipodimensaopneu',
            'criar_tipodimensaopneu',
            'editar_tipodimensaopneu',
            'excluir_tipodimensaopneu',
            'ver_tipoequipamento',
            'criar_tipoequipamento',
            'editar_tipoequipamento',
            'excluir_tipoequipamento',
            'ver_tipofornecedor',
            'criar_tipofornecedor',
            'editar_tipofornecedor',
            'excluir_tipofornecedor',
            'ver_tipoimobilizado',
            'criar_tipoimobilizado',
            'editar_tipoimobilizado',
            'excluir_tipoimobilizado',
            'ver_tipomanutencao',
            'criar_tipomanutencao',
            'editar_tipomanutencao',
            'excluir_tipomanutencao',
            'ver_tipomotivosinistro',
            'criar_tipomotivosinistro',
            'editar_tipomotivosinistro',
            'excluir_tipomotivosinistro',
            'ver_tipoocorrencia',
            'criar_tipoocorrencia',
            'editar_tipoocorrencia',
            'excluir_tipoocorrencia',
            'ver_tipooperacao',
            'criar_tipooperacao',
            'editar_tipooperacao',
            'excluir_tipooperacao',
            'ver_tipoorgaosinistro',
            'criar_tipoorgaosinistro',
            'editar_tipoorgaosinistro',
            'excluir_tipoorgaosinistro',
            'ver_tipopessoal',
            'criar_tipopessoal',
            'editar_tipopessoal',
            'excluir_tipopessoal',
            'ver_tiporeformapneu',
            'criar_tiporeformapneu',
            'editar_tiporeformapneu',
            'excluir_tiporeformapneu',
            'ver_tipostatuspreos',
            'criar_tipostatuspreos',
            'editar_tipostatuspreos',
            'excluir_tipostatuspreos',
            'ver_tipoveiculo',
            'criar_tipoveiculo',
            'editar_tipoveiculo',
            'excluir_tipoveiculo',

            // Departamentos
            'ver_departamento',
            'criar_departamento',
            'editar_departamento',
            'excluir_departamento',

            // Filiais
            'ver_filial',
            'criar_filial',
            'editar_filial',
            'excluir_filial',
            'ver_v_filial',
            'criar_v_filial',
            'editar_v_filial',
            'excluir_v_filial',
            'ver_vfilial',
            'criar_vfilial',
            'editar_vfilial',
            'excluir_vfilial',

            // Telefones
            'ver_telefone',
            'criar_telefone',
            'editar_telefone',
            'excluir_telefone',

            // Endereços
            'ver_endereco',
            'criar_endereco',
            'editar_endereco',
            'excluir_endereco',
            'ver_address',
            'criar_address',
            'editar_address',
            'excluir_address',

            // Estados/Municípios
            'ver_estado',
            'criar_estado',
            'editar_estado',
            'excluir_estado',
            'ver_municipio',
            'criar_municipio',
            'editar_municipio',
            'excluir_municipio',

            // Empresas
            'ver_empresa',
            'criar_empresa',
            'editar_empresa',
            'excluir_empresa',

            // Unidades
            'ver_unidadeproduto',
            'criar_unidadeproduto',
            'editar_unidadeproduto',
            'excluir_unidadeproduto',

            // Subcategorias
            'ver_subcategoriaveiculo',
            'criar_subcategoriaveiculo',
            'editar_subcategoriaveiculo',
            'excluir_subcategoriaveiculo',

            // Modelos
            'ver_modeloveiculo',
            'criar_modeloveiculo',
            'editar_modeloveiculo',
            'excluir_modeloveiculo',

            // Categorias de Serviço
            'ver_categoriaservico',
            'criar_categoriaservico',
            'editar_categoriaservico',
            'excluir_categoriaservico',

            // Grupos
            'ver_gruposervico',
            'criar_gruposervico',
            'editar_gruposervico',
            'excluir_gruposervico',
            'ver_subgruposervico',
            'criar_subgruposervico',
            'editar_subgruposervico',
            'excluir_subgruposervico',
            'ver_gruporesolvedor',
            'criar_gruporesolvedor',
            'editar_gruporesolvedor',
            'excluir_gruporesolvedor',

            // Metas
            'ver_metaportipoequipamento',
            'criar_metaportipoequipamento',
            'editar_metaportipoequipamento',
            'excluir_metaportipoequipamento',

            // Log de Atividades
            'ver_activitylog',
            'criar_activitylog',
            'editar_activitylog',
            'excluir_activitylog',
        ],

        // ========================================
        // USUÁRIOS E PERMISSÕES
        // ========================================
        'usuarios' => [
            'ver_user',
            'criar_user',
            'editar_user',
            'excluir_user',
            'ver_permission',
            'criar_permission',
            'editar_permission',
            'excluir_permission',
            'ver_permissiongroup',
            'criar_permissiongroup',
            'editar_permissiongroup',
            'excluir_permissiongroup',
            'ver_role',
            'criar_role',
            'editar_role',
            'excluir_role',
            'ver_cargousuario',
            'criar_cargousuario',
            'editar_cargousuario',
            'excluir_cargousuario',
            'ver_usuariodeparmanto',
            'criar_usuariodeparmanto',
            'editar_usuariodeparmanto',
            'excluir_usuariodeparmanto',
        ],

        // ========================================
        // NFE (NOTA FISCAL ELETRÔNICA)
        // ========================================
        'nfe' => [
            'ver_nfecore',
            'criar_nfecore',
            'editar_nfecore',
            'excluir_nfecore',
            'ver_nfedestinatario',
            'criar_nfedestinatario',
            'editar_nfedestinatario',
            'excluir_nfedestinatario',
            'ver_nfeemissor',
            'criar_nfeemissor',
            'editar_nfeemissor',
            'excluir_nfeemissor',
            'ver_nfefatura',
            'criar_nfefatura',
            'editar_nfefatura',
            'excluir_nfefatura',
            'ver_nfeproduto',
            'criar_nfeproduto',
            'editar_nfeproduto',
            'excluir_nfeproduto',
            'ver_nfetransportadora',
            'criar_nfetransportadora',
            'editar_nfetransportadora',
            'excluir_nfetransportadora',
            'ver_basenfemodel',
            'criar_basenfemodel',
            'editar_basenfemodel',
            'excluir_basenfemodel',
        ],

        // ========================================
        // OUTROS/DIVERSOS
        // ========================================
        'diversos' => [
            // Branch
            'ver_branch',
            'criar_branch',
            'editar_branch',
            'excluir_branch',

            // Registro Compra/Venda
            'ver_registrocompravenda',
            'criar_registrocompravenda',
            'editar_registrocompravenda',
            'excluir_registrocompravenda',
        ],
    ],

    /**
     * Mapeamento de permissões especiais que não seguem o padrão ver/criar/editar/excluir
     * PADRONIZAÇÃO: Todas seguem o padrão {acao}_{modulo}_{especificacao}
     */
    'special_permissions' => [
        'compras' => [
            // Aprovações padronizadas
            'aprovar_nota_fiscal_compras',
            'aprovar_orcamento_compras',
            'aprovar_pedido_compras',
            'aprovar_pedido_compras_nivel_1',
            'aprovar_pedido_compras_nivel_2',
            'aprovar_pedido_compras_nivel_3',
            'aprovar_pedido_compras_nivel_4',
            'aprovar_solicitacao_compras',

            // Ações especiais padronizadas
            'cancelar_pedido_compras',
            'enviar_pedido_compras',
            'rejeitar_orcamento_compras',
            'rejeitar_pedido_compras',
            'rejeitar_solicitacao_compras',
            'exportar_relatorios_compras',

            // Visualizações específicas (mantidas para compatibilidade)
            'visualizar_contrato_compras',
            'visualizar_fornecedor_compras',
            'visualizar_nota_fiscal_compras',
            'visualizar_orcamento_compras',
            'visualizar_pedido_compras',
            'visualizar_relatorios_compras',
            'visualizar_solicitacao_compras',
            'visualizar_requisicao_material',
        ],

        'abastecimentos' => [
            // Aprovações de abastecimento
            'aprovar_abastecimento_manual',
            'aprovar_ajuste_km_abastecimento',
            'validar_inconsistencia_ats',
            'validar_inconsistencia_truckpag',
            'autorizar_km_manual',
            'processar_integracao_abastecimento',
        ],

        'veiculos' => [
            // Transferências e movimentações
            'aprovar_transferencia_veiculo',
            'autorizar_baixa_veiculo',
            'processar_licenciamento_veiculo',
            'renovar_ipva_veiculo',
            'validar_certificado_veiculo',
        ],

        'estoque' => [
            // Movimentações especiais
            'aprovar_transferencia_estoque',
            'autorizar_ajuste_estoque',
            'processar_devolucao_estoque',
            'validar_inventario_estoque',

            // Requisições de materiais
            'aprovar_requisicao_material',
            'rejeitar_requisicao_material',
            'cancelar_requisicao_material',
            'finalizar_requisicao_material',
        ],

        'manutencao' => [
            // Aprovações de manutenção
            'aprovar_ordem_servico',
            'autorizar_manutencao_preventiva',
            'finalizar_ordem_servico',
            'reprovar_servico_manutencao',
        ],

        'pneus' => [
            // Movimentações de pneus
            'aprovar_transferencia_pneus',
            'autorizar_descarte_pneus',
            'processar_recapagem_pneus',
            'validar_medicao_pneus',
        ],
    ],

    /**
     * Grupos de permissões por funcionalidade
     * Útil para aplicar em menus específicos
     */
    'permission_groups' => [
        'visualizacao' => [
            // Todas as permissões VER
            'ver_abastecimento',
            'ver_abastecimentoatstruckpagmanual',
            'ver_abastecimentointegracao',
            'ver_abastecimentoitem',
            'ver_abastecimentomanual',
            'ver_abastecimentosfaturamento',
            'ver_abastecimentotruckpag',
            'ver_activitylog',
            'ver_address',
            'ver_ajusteestoque',
            'ver_ajustekmabastecimento',
            'ver_atrelamentoitens',
            'ver_atrelamentoveiculo',
            'ver_basenfemodel',
            'ver_baseveiculo',
            'ver_bomba',
            'ver_branch',
            'ver_cargousuario',
            'ver_categoriaplanejamentomanutencao',
            'ver_categoriaservico',
            'ver_certificadoveiculos',
            'ver_checklist',
            'ver_checklistresposta',
            'ver_classificacaomulta',
            'ver_colunachecklist',
            'ver_contagempneu',
            'ver_dadospessoalsinistro',
            'ver_departamento',
            'ver_descartepneu',
            'ver_despesasveiculos',
            'ver_detalhemulta',
            'ver_devolucaomateriais',
            'ver_devolucaoprodutoordem',
            'ver_devolucaotransferenciaestoquerequisicao',
            'ver_empresa',
            'ver_encerrante',
            'ver_endereco',
            'ver_entradaafericaoabastecimento',
            'ver_estado',
            'ver_estoque',
            'ver_estoquecombustivel',
            'ver_filial',
            'ver_fornecedor',
            'ver_fornecedorxmecanico',
            'ver_fotosdocumentossinistros',
            'ver_gruporesolvedor',
            'ver_gruposervico',
            'ver_historicoabastecimentobaixarestoque',
            'ver_historicoeventossinistro',
            'ver_historicomovimentacaoestoque',
            'ver_historicopneu',
            'ver_inconsistenciaats',
            'ver_inconsistenciatruckpag',
            'ver_ipvaveiculo',
            'ver_itenspedidos',
            'ver_kmcomotado',
            'ver_licenciamentoveiculo',
            'ver_manutencao',
            'ver_manutencaopneus',
            'ver_manutencaopneusentrada',
            'ver_manutencaopneusentradaitens',
            'ver_manutencaopneusitens',
            'ver_metaportipoequipamento',
            'ver_modelopneu',
            'ver_modeloveiculo',
            'ver_motorista',
            'ver_multa',
            'ver_municipio',
            'ver_nfecore',
            'ver_nfedestinatario',
            'ver_nfeemissor',
            'ver_nfefatura',
            'ver_nfeproduto',
            'ver_nfetransportadora',
            'ver_nfordemservico',
            'ver_notafiscalservico',
            'ver_notafiscalservicoitens',
            'ver_ordemservico',
            'ver_ordemservicopecas',
            'ver_ordemservicopecasimobilizados',
            'ver_ordemservicoservicos',
            'ver_parcelasipva',
            'ver_pecasservicos',
            'ver_pedidocompras',
            'ver_permissaokmmanual',
            'ver_permission',
            'ver_permissiongroup',
            'ver_pessoal',
            'ver_planejamentomanutencao',
            'ver_pneu',
            'ver_pneusaplicados',
            'ver_preordemservico',
            'ver_preordemservicoservicos',
            'ver_produto',
            'ver_produtoporfilial',
            'ver_produtosporfilial',
            'ver_produtossolicitacoes',
            'ver_produtoxaplicacao',
            'ver_requisicaomaterial',
            'ver_recebimentocombustivel',
            'ver_registrocompravenda',
            'ver_relacaoimobilizado',
            'ver_relacaoimobilizadoitens',
            'ver_relacaosolicitacaoespecas',
            'ver_requisicaopneu',
            'ver_requisicaopneuitens',
            'ver_requisicaopneumodelos',
            'ver_role',
            'ver_seguroobrigatorio',
            'ver_servico',
            'ver_servicoplanejamentomanutencao',
            'ver_servicos',
            'ver_servicosmecanico',
            'ver_servicoxfornecedor',
            'ver_sinistro',
            'ver_solicitacaocompras',
            'ver_statusordemservico',
            'ver_subcategoriaveiculo',
            'ver_subgruposervico',
            'ver_tanque',
            'ver_telefone',
            'ver_testefumaca',
            'ver_tipoacertoestoque',
            'ver_tipoborrachapneu',
            'ver_tipocategoria',
            'ver_tipocertificado',
            'ver_tipochecklist',
            'ver_tipocombustivel',
            'ver_tipodescarte',
            'ver_tipodesenhopneu',
            'ver_tipodespesas',
            'ver_tipodimensaopneu',
            'ver_tipoequipamento',
            'ver_tipofornecedor',
            'ver_tipoimobilizado',
            'ver_tipomanutencao',
            'ver_tipomanutencaoimobilizado',
            'ver_tipomotivosinistro',
            'ver_tipoocorrencia',
            'ver_tipooperacao',
            'ver_tipoorgaosinistro',
            'ver_tipopessoal',
            'ver_tiporeformapneu',
            'ver_tipostatuspreos',
            'ver_tipoveiculo',
            'ver_transferenciadiretaestoque',
            'ver_transferenciaestoque',
            'ver_transferenciaestoqueaux',
            'ver_transferenciaestoqueauxenvio',
            'ver_transferenciaestoqueitens',
            'ver_transferenciapneuitens',
            'ver_transferenciapneus',
            'ver_transferenciapneusmodelos',
            'ver_transferenciaveiculo',
            'ver_unidadeproduto',
            'ver_user',
            'ver_usuariodeparmanto',
            'ver_valorcombustivelterceiro',
            'ver_vcontrolemanutencaofrota',
            'ver_veiculo',
            'ver_veiculoxpneu',
            'ver_vestoquecombustivel',
            'ver_v_filial',
            'ver_vfilial',
            'ver_v_manutencao_abertas',
            'ver_vrequisicaoprodutoos',
            'ver_vultimasmanutencoesveiculo',
            'ver_vultimaspreventivasveiculo',
            'ver_vvlratualabastecimento',

            // Permissões VISUALIZAR
            'visualizar_contrato',
            'visualizar_fornecedor',
            'visualizar_nota_fiscal',
            'visualizar_orcamento',
            'visualizar_pedido_compra',
            'visualizar_relatorios_compras',
            'visualizar_solicitacao_compra',
            'visualizar_requisicao_material',
        ],

        'criacao' => [
            // Todas as permissões CRIAR
            'criar_abastecimento',
            'criar_abastecimentoatstruckpagmanual',
            'criar_abastecimentointegracao',
            'criar_abastecimentoitem',
            'criar_abastecimentomanual',
            'criar_abastecimentosfaturamento',
            'criar_abastecimentotruckpag',
            'criar_activitylog',
            'criar_address',
            'criar_ajusteestoque',
            'criar_ajustekmabastecimento',
            'criar_atrelamentoitens',
            'criar_atrelamentoveiculo',
            'criar_basenfemodel',
            'criar_baseveiculo',
            'criar_bomba',
            'criar_branch',
            'criar_cargousuario',
            'criar_categoriaplanejamentomanutencao',
            'criar_categoriaservico',
            'criar_certificadoveiculos',
            'criar_checklist',
            'criar_checklistresposta',
            'criar_classificacaomulta',
            'criar_colunachecklist',
            'criar_contagempneu',
            'criar_contrato',
            'criar_dadospessoalsinistro',
            'criar_departamento',
            'criar_descartepneu',
            'criar_despesasveiculos',
            'criar_detalhemulta',
            'criar_devolucaomateriais',
            'criar_devolucaoprodutoordem',
            'criar_devolucaotransferenciaestoquerequisicao',
            'criar_empresa',
            'criar_encerrante',
            'criar_endereco',
            'criar_entradaafericaoabastecimento',
            'criar_estado',
            'criar_estoque',
            'criar_estoquecombustivel',
            'criar_filial',
            'criar_fornecedor',
            'criar_fornecedorxmecanico',
            'criar_fotosdocumentossinistros',
            'criar_gruporesolvedor',
            'criar_gruposervico',
            'criar_historicoabastecimentobaixarestoque',
            'criar_historicoeventossinistro',
            'criar_historicomovimentacaoestoque',
            'criar_historicopneu',
            'criar_inconsistenciaats',
            'criar_inconsistenciatruckpag',
            'criar_ipvaveiculo',
            'criar_itenspedidos',
            'criar_kmcomotado',
            'criar_licenciamentoveiculo',
            'criar_manutencao',
            'criar_manutencaopneus',
            'criar_manutencaopneusentrada',
            'criar_manutencaopneusentradaitens',
            'criar_manutencaopneusitens',
            'criar_metaportipoequipamento',
            'criar_modelopneu',
            'criar_modeloveiculo',
            'criar_motorista',
            'criar_multa',
            'criar_municipio',
            'criar_nfecore',
            'criar_nfedestinatario',
            'criar_nfeemissor',
            'criar_nfefatura',
            'criar_nfeproduto',
            'criar_nfetransportadora',
            'criar_nfordemservico',
            'criar_nota_fiscal',
            'criar_notafiscalservico',
            'criar_notafiscalservicoitens',
            'criar_orcamento',
            'criar_ordemservico',
            'criar_ordemservicopecas',
            'criar_ordemservicopecasimobilizados',
            'criar_ordemservicoservicos',
            'criar_parcelasipva',
            'criar_pecasservicos',
            'criar_pedido_compra',
            'criar_pedidocompras',
            'criar_permissaokmmanual',
            'criar_permission',
            'criar_permissiongroup',
            'criar_pessoal',
            'criar_planejamentomanutencao',
            'criar_pneu',
            'criar_pneusaplicados',
            'criar_preordemservico',
            'criar_preordemservicoservicos',
            'criar_produto',
            'criar_produtoporfilial',
            'criar_produtosporfilial',
            'criar_produtossolicitacoes',
            'criar_produtoxaplicacao',
            'criar_requisicao_material',
            'criar_recebimentocombustivel',
            'criar_registrocompravenda',
            'criar_relacaoimobilizado',
            'criar_relacaoimobilizadoitens',
            'criar_relacaosolicitacaoespecas',
            'criar_requisicaopneu',
            'criar_requisicaopneuitens',
            'criar_requisicaopneumodelos',
            'criar_role',
            'criar_seguroobrigatorio',
            'criar_servico',
            'criar_servicoplanejamentomanutencao',
            'criar_servicos',
            'criar_servicosmecanico',
            'criar_servicoxfornecedor',
            'criar_sinistro',
            'criar_solicitacao_compra',
            'criar_solicitacaocompras',
            'criar_statusordemservico',
            'criar_subcategoriaveiculo',
            'criar_subgruposervico',
            'criar_tanque',
            'criar_telefone',
            'criar_testefumaca',
            'criar_tipoacertoestoque',
            'criar_tipoborrachapneu',
            'criar_tipocategoria',
            'criar_tipocertificado',
            'criar_tipochecklist',
            'criar_tipocombustivel',
            'criar_tipodescarte',
            'criar_tipodesenhopneu',
            'criar_tipodespesas',
            'criar_tipodimensaopneu',
            'criar_tipoequipamento',
            'criar_tipofornecedor',
            'criar_tipoimobilizado',
            'criar_tipomanutencao',
            'criar_tipomanutencaoimobilizado',
            'criar_tipomotivosinistro',
            'criar_tipoocorrencia',
            'criar_tipooperacao',
            'criar_tipoorgaosinistro',
            'criar_tipopessoal',
            'criar_tiporeformapneu',
            'criar_tipostatuspreos',
            'criar_tipoveiculo',
            'criar_transferenciadiretaestoque',
            'criar_transferenciaestoque',
            'criar_transferenciaestoqueaux',
            'criar_transferenciaestoqueauxenvio',
            'criar_transferenciaestoqueitens',
            'criar_transferenciapneuitens',
            'criar_transferenciapneus',
            'criar_transferenciapneusmodelos',
            'criar_transferenciaveiculo',
            'criar_unidadeproduto',
            'criar_user',
            'criar_usuariodeparmanto',
            'criar_valorcombustivelterceiro',
            'criar_vcontrolemanutencaofrota',
            'criar_veiculo',
            'criar_veiculoxpneu',
            'criar_vestoquecombustivel',
            'criar_v_filial',
            'criar_vfilial',
            'criar_v_manutencao_abertas',
            'criar_vrequisicaoprodutoos',
            'criar_vultimasmanutencoesveiculo',
            'criar_vultimaspreventivasveiculo',
            'criar_vvlratualabastecimento',
        ],

        'edicao' => [
            // Todas as permissões EDITAR
            'editar_abastecimento',
            'editar_abastecimentoatstruckpagmanual',
            'editar_abastecimentointegracao',
            'editar_abastecimentoitem',
            'editar_abastecimentomanual',
            'editar_abastecimentosfaturamento',
            'editar_abastecimentotruckpag',
            'editar_activitylog',
            'editar_address',
            'editar_ajusteestoque',
            'editar_ajustekmabastecimento',
            'editar_atrelamentoitens',
            'editar_atrelamentoveiculo',
            'editar_basenfemodel',
            'editar_baseveiculo',
            'editar_bomba',
            'editar_branch',
            'editar_cargousuario',
            'editar_categoriaplanejamentomanutencao',
            'editar_categoriaservico',
            'editar_certificadoveiculos',
            'editar_checklist',
            'editar_checklistresposta',
            'editar_classificacaomulta',
            'editar_colunachecklist',
            'editar_contagempneu',
            'editar_contrato',
            'editar_dadospessoalsinistro',
            'editar_departamento',
            'editar_descartepneu',
            'editar_despesasveiculos',
            'editar_detalhemulta',
            'editar_devolucaomateriais',
            'editar_devolucaoprodutoordem',
            'editar_devolucaotransferenciaestoquerequisicao',
            'editar_empresa',
            'editar_encerrante',
            'editar_endereco',
            'editar_entradaafericaoabastecimento',
            'editar_estado',
            'editar_estoque',
            'editar_estoquecombustivel',
            'editar_filial',
            'editar_fornecedor',
            'editar_fornecedorxmecanico',
            'editar_fotosdocumentossinistros',
            'editar_gruporesolvedor',
            'editar_gruposervico',
            'editar_historicoabastecimentobaixarestoque',
            'editar_historicoeventossinistro',
            'editar_historicomovimentacaoestoque',
            'editar_historicopneu',
            'editar_inconsistenciaats',
            'editar_inconsistenciatruckpag',
            'editar_ipvaveiculo',
            'editar_itenspedidos',
            'editar_kmcomotado',
            'editar_licenciamentoveiculo',
            'editar_manutencao',
            'editar_manutencaopneus',
            'editar_manutencaopneusentrada',
            'editar_manutencaopneusentradaitens',
            'editar_manutencaopneusitens',
            'editar_metaportipoequipamento',
            'editar_modelopneu',
            'editar_modeloveiculo',
            'editar_motorista',
            'editar_multa',
            'editar_municipio',
            'editar_nfecore',
            'editar_nfedestinatario',
            'editar_nfeemissor',
            'editar_nfefatura',
            'editar_nfeproduto',
            'editar_nfetransportadora',
            'editar_nfordemservico',
            'editar_nota_fiscal',
            'editar_notafiscalservico',
            'editar_notafiscalservicoitens',
            'editar_orcamento',
            'editar_ordemservico',
            'editar_ordemservicopecas',
            'editar_ordemservicopecasimobilizados',
            'editar_ordemservicoservicos',
            'editar_parcelasipva',
            'editar_pecasservicos',
            'editar_pedido_compra',
            'editar_pedidocompras',
            'editar_permissaokmmanual',
            'editar_permission',
            'editar_permissiongroup',
            'editar_pessoal',
            'editar_planejamentomanutencao',
            'editar_pneu',
            'editar_pneusaplicados',
            'editar_preordemservico',
            'editar_preordemservicoservicos',
            'editar_produto',
            'editar_produtoporfilial',
            'editar_produtosporfilial',
            'editar_produtossolicitacoes',
            'editar_produtoxaplicacao',
            'editar_requisicao_material',
            'editar_recebimentocombustivel',
            'editar_registrocompravenda',
            'editar_relacaoimobilizado',
            'editar_relacaoimobilizadoitens',
            'editar_relacaosolicitacaoespecas',
            'editar_requisicaopneu',
            'editar_requisicaopneuitens',
            'editar_requisicaopneumodelos',
            'editar_role',
            'editar_seguroobrigatorio',
            'editar_servico',
            'editar_servicoplanejamentomanutencao',
            'editar_servicos',
            'editar_servicosmecanico',
            'editar_servicoxfornecedor',
            'editar_sinistro',
            'editar_solicitacao_compra',
            'editar_solicitacaocompras',
            'editar_statusordemservico',
            'editar_subcategoriaveiculo',
            'editar_subgruposervico',
            'editar_tanque',
            'editar_telefone',
            'editar_testefumaca',
            'editar_tipoacertoestoque',
            'editar_tipoborrachapneu',
            'editar_tipocategoria',
            'editar_tipocertificado',
            'editar_tipochecklist',
            'editar_tipocombustivel',
            'editar_tipodescarte',
            'editar_tipodesenhopneu',
            'editar_tipodespesas',
            'editar_tipodimensaopneu',
            'editar_tipoequipamento',
            'editar_tipofornecedor',
            'editar_tipoimobilizado',
            'editar_tipomanutencao',
            'editar_tipomanutencaoimobilizado',
            'editar_tipomotivosinistro',
            'editar_tipoocorrencia',
            'editar_tipooperacao',
            'editar_tipoorgaosinistro',
            'editar_tipopessoal',
            'editar_tiporeformapneu',
            'editar_tipostatuspreos',
            'editar_tipoveiculo',
            'editar_transferenciadiretaestoque',
            'editar_transferenciaestoque',
            'editar_transferenciaestoqueaux',
            'editar_transferenciaestoqueauxenvio',
            'editar_transferenciaestoqueitens',
            'editar_transferenciapneuitens',
            'editar_transferenciapneus',
            'editar_transferenciapneusmodelos',
            'editar_transferenciaveiculo',
            'editar_unidadeproduto',
            'editar_user',
            'editar_usuariodeparmanto',
            'editar_valorcombustivelterceiro',
            'editar_vcontrolemanutencaofrota',
            'editar_veiculo',
            'editar_veiculoxpneu',
            'editar_vestoquecombustivel',
            'editar_v_filial',
            'editar_vfilial',
            'editar_v_manutencao_abertas',
            'editar_vrequisicaoprodutoos',
            'editar_vultimasmanutencoesveiculo',
            'editar_vultimaspreventivasveiculo',
            'editar_vvlratualabastecimento',
        ],

        'exclusao' => [
            // Todas as permissões EXCLUIR
            'excluir_abastecimento',
            'excluir_abastecimentoatstruckpagmanual',
            'excluir_abastecimentointegracao',
            'excluir_abastecimentoitem',
            'excluir_abastecimentomanual',
            'excluir_abastecimentosfaturamento',
            'excluir_abastecimentotruckpag',
            'excluir_activitylog',
            'excluir_address',
            'excluir_ajusteestoque',
            'excluir_ajustekmabastecimento',
            'excluir_atrelamentoitens',
            'excluir_atrelamentoveiculo',
            'excluir_basenfemodel',
            'excluir_baseveiculo',
            'excluir_bomba',
            'excluir_branch',
            'excluir_cargousuario',
            'excluir_categoriaplanejamentomanutencao',
            'excluir_categoriaservico',
            'excluir_certificadoveiculos',
            'excluir_checklist',
            'excluir_checklistresposta',
            'excluir_classificacaomulta',
            'excluir_colunachecklist',
            'excluir_contagempneu',
            'excluir_contrato',
            'excluir_dadospessoalsinistro',
            'excluir_departamento',
            'excluir_descartepneu',
            'excluir_despesasveiculos',
            'excluir_detalhemulta',
            'excluir_devolucaomateriais',
            'excluir_devolucaoprodutoordem',
            'excluir_devolucaotransferenciaestoquerequisicao',
            'excluir_empresa',
            'excluir_encerrante',
            'excluir_endereco',
            'excluir_entradaafericaoabastecimento',
            'excluir_estado',
            'excluir_estoque',
            'excluir_estoquecombustivel',
            'excluir_filial',
            'excluir_fornecedor',
            'excluir_fornecedorxmecanico',
            'excluir_fotosdocumentossinistros',
            'excluir_gruporesolvedor',
            'excluir_gruposervico',
            'excluir_historicoabastecimentobaixarestoque',
            'excluir_historicoeventossinistro',
            'excluir_historicomovimentacaoestoque',
            'excluir_historicopneu',
            'excluir_inconsistenciaats',
            'excluir_inconsistenciatruckpag',
            'excluir_ipvaveiculo',
            'excluir_itenspedidos',
            'excluir_kmcomotado',
            'excluir_licenciamentoveiculo',
            'excluir_manutencao',
            'excluir_manutencaopneus',
            'excluir_manutencaopneusentrada',
            'excluir_manutencaopneusentradaitens',
            'excluir_manutencaopneusitens',
            'excluir_metaportipoequipamento',
            'excluir_modelopneu',
            'excluir_modeloveiculo',
            'excluir_motorista',
            'excluir_multa',
            'excluir_municipio',
            'excluir_nfecore',
            'excluir_nfedestinatario',
            'excluir_nfeemissor',
            'excluir_nfefatura',
            'excluir_nfeproduto',
            'excluir_nfetransportadora',
            'excluir_nfordemservico',
            'excluir_nota_fiscal',
            'excluir_notafiscalservico',
            'excluir_notafiscalservicoitens',
            'excluir_orcamento',
            'excluir_ordemservico',
            'excluir_ordemservicopecas',
            'excluir_ordemservicopecasimobilizados',
            'excluir_ordemservicoservicos',
            'excluir_parcelasipva',
            'excluir_pecasservicos',
            'excluir_pedido_compra',
            'excluir_pedidocompras',
            'excluir_permissaokmmanual',
            'excluir_permission',
            'excluir_permissiongroup',
            'excluir_pessoal',
            'excluir_planejamentomanutencao',
            'excluir_pneu',
            'excluir_pneusaplicados',
            'excluir_preordemservico',
            'excluir_preordemservicoservicos',
            'excluir_produto',
            'excluir_produtoporfilial',
            'excluir_produtosporfilial',
            'excluir_produtossolicitacoes',
            'excluir_produtoxaplicacao',
            'excluir_requisicao_material',
            'excluir_recebimentocombustivel',
            'excluir_registrocompravenda',
            'excluir_relacaoimobilizado',
            'excluir_relacaoimobilizadoitens',
            'excluir_relacaosolicitacaoespecas',
            'excluir_requisicaopneu',
            'excluir_requisicaopneuitens',
            'excluir_requisicaopneumodelos',
            'excluir_role',
            'excluir_seguroobrigatorio',
            'excluir_servico',
            'excluir_servicoplanejamentomanutencao',
            'excluir_servicos',
            'excluir_servicosmecanico',
            'excluir_servicoxfornecedor',
            'excluir_sinistro',
            'excluir_solicitacao_compra',
            'excluir_solicitacaocompras',
            'excluir_statusordemservico',
            'excluir_subcategoriaveiculo',
            'excluir_subgruposervico',
            'excluir_tanque',
            'excluir_telefone',
            'excluir_testefumaca',
            'excluir_tipoacertoestoque',
            'excluir_tipoborrachapneu',
            'excluir_tipocategoria',
            'excluir_tipocertificado',
            'excluir_tipochecklist',
            'excluir_tipocombustivel',
            'excluir_tipodescarte',
            'excluir_tipodesenhopneu',
            'excluir_tipodespesas',
            'excluir_tipodimensaopneu',
            'excluir_tipoequipamento',
            'excluir_tipofornecedor',
            'excluir_tipoimobilizado',
            'excluir_tipomanutencao',
            'excluir_tipomanutencaoimobilizado',
            'excluir_tipomotivosinistro',
            'excluir_tipoocorrencia',
            'excluir_tipooperacao',
            'excluir_tipoorgaosinistro',
            'excluir_tipopessoal',
            'excluir_tiporeformapneu',
            'excluir_tipostatuspreos',
            'excluir_tipoveiculo',
            'excluir_transferenciadiretaestoque',
            'excluir_transferenciaestoque',
            'excluir_transferenciaestoqueaux',
            'excluir_transferenciaestoqueauxenvio',
            'excluir_transferenciaestoqueitens',
            'excluir_transferenciapneuitens',
            'excluir_transferenciapneus',
            'excluir_transferenciapneusmodelos',
            'excluir_transferenciaveiculo',
            'excluir_unidadeproduto',
            'excluir_user',
            'excluir_usuariodeparmanto',
            'excluir_valorcombustivelterceiro',
            'excluir_vcontrolemanutencaofrota',
            'excluir_veiculo',
            'excluir_veiculoxpneu',
            'excluir_vestoquecombustivel',
            'excluir_v_filial',
            'excluir_vfilial',
            'excluir_v_manutencao_abertas',
            'excluir_vrequisicaoprodutoos',
            'excluir_vultimasmanutencoesveiculo',
            'excluir_vultimaspreventivasveiculo',
            'excluir_vvlratualabastecimento',
        ],

        'aprovacao' => [
            // Todas as permissões APROVAR
            'aprovar_nota_fiscal',
            'aprovar_orcamento',
            'aprovar_pedido_compra',
            'aprovar_pedido_compra_nivel_1',
            'aprovar_pedido_compra_nivel_2',
            'aprovar_pedido_compra_nivel_3',
            'aprovar_pedido_compra_nivel_4',
            'aprovar_solicitacao_compra',
        ],

        'rejeicao' => [
            // Todas as permissões REJEITAR
            'rejeitar_orcamento',
            'rejeitar_pedido_compra',
            'rejeitar_solicitacao_compra',
        ],

        'cancelamento' => [
            // Todas as permissões CANCELAR
            'cancelar_pedido_compra',
        ],

        'envio' => [
            // Todas as permissões ENVIAR
            'enviar_pedido_compra',
        ],

        'exportacao' => [
            // Todas as permissões EXPORTAR
            'exportar_relatorios_compras',
        ],
    ],

    /**
     * Mapeamento de rotas para permissões
     * Útil para middleware automático
     */
    'route_permissions' => [
        // Abastecimentos
        'admin.abastecimentomanual.*' => ['ver_abastecimentomanual', 'criar_abastecimentomanual', 'editar_abastecimentomanual'],
        'admin.abastecimentosatstruckpagmanual.*' => ['ver_abastecimentoatstruckpagmanual', 'criar_abastecimentoatstruckpagmanual', 'editar_abastecimentoatstruckpagmanual'],
        'admin.ajustekm.*' => ['ver_ajustekmabastecimento', 'criar_ajustekmabastecimento', 'editar_ajustekmabastecimento'],
        'admin.encerrantes.*' => ['ver_encerrante', 'criar_encerrante', 'editar_encerrante'],
        'admin.bombas.*' => ['ver_bomba', 'criar_bomba', 'editar_bomba'],

        // Veículos
        'admin.veiculos.*' => ['ver_veiculo', 'criar_veiculo', 'editar_veiculo'],
        'admin.licenciamentoveiculos.*' => ['ver_licenciamentoveiculo', 'criar_licenciamentoveiculo', 'editar_licenciamentoveiculo'],
        'admin.ipvaveiculos.*' => ['ver_ipvaveiculo', 'criar_ipvaveiculo', 'editar_ipvaveiculo'],

        // Estoque
        'admin.estoque.*' => ['ver_estoque', 'criar_estoque', 'editar_estoque'],
        'admin.cadastroprodutosestoque.*' => ['ver_produto', 'criar_produto', 'editar_produto'],
        'admin.saidaprodutosestoque.*' => ['ver_produto', 'criar_produto', 'editar_produto'],

        // Manutenção
        'admin.ordemservicos.*' => ['ver_ordemservico', 'criar_ordemservico', 'editar_ordemservico'],
        'admin.manutencaoservicosmecanico.*' => ['ver_servicosmecanico', 'criar_servicosmecanico', 'editar_servicosmecanico'],

        // Pneus
        'admin.pneus.*' => ['ver_pneu', 'criar_pneu', 'editar_pneu'],
        'admin.contagempneus.*' => ['ver_contagempneu', 'criar_contagempneu', 'editar_contagempneu'],

        // Pessoal
        'admin.pessoas.*' => ['ver_pessoal', 'criar_pessoal', 'editar_pessoal'],
        'admin.fornecedores.*' => ['ver_fornecedor', 'criar_fornecedor', 'editar_fornecedor'],

        // Configurações
        'admin.usuarios.*' => ['ver_user', 'criar_user', 'editar_user'],
        'admin.permissoes.*' => ['ver_permission', 'criar_permission', 'editar_permission'],
        'admin.cargos.*' => ['ver_role', 'criar_role', 'editar_role'],
        'admin.filiais.*' => ['ver_filial', 'criar_filial', 'editar_filial'],
        'admin.departamentos.*' => ['ver_departamento', 'criar_departamento', 'editar_departamento'],

        // Tipos (Configurações)
        'admin.tipoacertoestoque.*' => ['ver_tipoacertoestoque', 'criar_tipoacertoestoque', 'editar_tipoacertoestoque'],
        'admin.tipoborrachapneus.*' => ['ver_tipoborrachapneu', 'criar_tipoborrachapneu', 'editar_tipoborrachapneu'],
        'admin.tipocategorias.*' => ['ver_tipocategoria', 'criar_tipocategoria', 'editar_tipocategoria'],
        'admin.tipocombustiveis.*' => ['ver_tipocombustivel', 'criar_tipocombustivel', 'editar_tipocombustivel'],
        'admin.tipoequipamentos.*' => ['ver_tipoequipamento', 'criar_tipoequipamento', 'editar_tipoequipamento'],
        'admin.tipofornecedores.*' => ['ver_tipofornecedor', 'criar_tipofornecedor', 'editar_tipofornecedor'],
        'admin.tipoimobilizados.*' => ['ver_tipoimobilizado', 'criar_tipoimobilizado', 'editar_tipoimobilizado'],
        'admin.tipomanutencoes.*' => ['ver_tipomanutencao', 'criar_tipomanutencao', 'editar_tipomanutencao'],
        'admin.tipoveiculos.*' => ['ver_tipoveiculo', 'criar_tipoveiculo', 'editar_tipoveiculo'],

        // Compras
        'admin.compras.*' => ['ver_solicitacaocompras', 'criar_solicitacao_compra', 'editar_solicitacao_compra'],

        // Sinistros
        'admin.sinistros.*' => ['ver_sinistro', 'criar_sinistro', 'editar_sinistro'],

        // Multas
        'admin.multas.*' => ['ver_multa', 'criar_multa', 'editar_multa'],
        'admin.classificacaomultas.*' => ['ver_classificacaomulta', 'criar_classificacaomulta', 'editar_classificacaomulta'],
    ],

    /**
     * Configurações de cache para permissões
     */
    'cache' => [
        'enabled' => true,
        'ttl' => 3600, // 1 hora em segundos
        'key_prefix' => 'permissions_',
    ],

    /**
     * Configurações de fallback
     */
    'fallback' => [
        'redirect_route' => 'admin.dashboard',
        'show_unauthorized_message' => true,
        'unauthorized_message' => 'Você não tem permissão para acessar esta funcionalidade.',
    ],

];
